### ISSUE TITLE
Can't install lmoments3 with conda 4.6.10 on Win10-64bit

### ISSUE THREAD

**Issue by slipfall** [cqcn1991/Wind-Speed-Analysis#4]
requirements.txt includes lmoments3

but lmoments3 will not install - with conda 4.6.10 on Win10-64bit
error:
(base) C:\Users\slipfall>conda install --channel "openhydrology" lmoments3
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - conda[version='>=4.6.10']
  - lmoments3
Use "conda search <package> --info" to see the dependencies for each package.

**Comment by 0xzkzhao** [comment]
Well, can you get the barebone_fitter.ipynb running? (as I remember, it does not require lmoments3). but sadly, I don't have a good solution to this. Maybe using a lower version for conda may help?
